# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_origin', models.CharField(max_length=20)),
                ('product_brand', models.CharField(max_length=50)),
                ('product_description', models.TextField(max_length=1000)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_image', models.URLField()),
            ],
        ),
    ]
