# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170909_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_origin',
        ),
    ]
